# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  helloapijen:
    image: helloapijen
    build:
      context: .
      dockerfile: HelloApiPipeline/HelloAPiJen/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5179:5179
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
